# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea0635c35db3c87cc3a28a2a6ef2f20468949a65c485df4e4168c2936b1eef2efbbfbf6e11e98c161bd0b669ac07db011d4e0553e6ba81ecfec1e0c2e6e0e87

test:
  secret_key_base: e5ddf325ec708a5947c2acd8818cf2dfe7a9baff13ad1a0287fcc0f7cbf6a3b4eaf6993d5b0dc0856d82446c1b0ca7f4e4d13cf49109e35b9fe602f3e3d0164b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
